export const RowData = [
  {
    "@odata.etag": "W/\"94859327\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "09/15/2022",
    "mod@ified.on": "2022-09-15T05:00:21Z",
    "name": "*MASTER ELECTRIC-5/17/2022-Advanced Voice - SIP",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "64b3491d-e1e3-4585-9627-b05b632dc455",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "*MASTER ELECTRIC"
  },
  {
    "@odata.etag": "W/\"95274789\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "09/19/2022",
    "mod@ified.on": "2022-09-19T05:00:28Z",
    "name": "COMCAST-6/22/2022-Advanced Voice - Trunking",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "a893fb41-93d9-410b-942a-a569a8664556",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "COMCAST"
  },
  {
    "@odata.etag": "W/\"101855607\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "11/28/2022",
    "mod@ified.on": "2022-11-28T06:00:27Z",
    "name": "COMCAST-6/16/2022",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "8b32ec51-7bed-ec11-bb3d-00224822760c",
    "actualvalue@OData.Community.Display.V1.FormattedValue": "$2,953.90",
    "actualvalue": 2953.9,
    "estimatedclosedate@OData.Community.Display.V1.FormattedValue": "09/14/2022",
    "estimatedclosedate": "2022-09-14",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "COMCAST"
  },
  {
    "@odata.etag": "W/\"102539097\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "12/08/2022",
    "mod@ified.on": "2022-12-08T16:02:43Z",
    "name": "-12/8/2022",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "6eb11c79-432e-4a36-8be0-32053804db38",
    "estimatedclosedate@OData.Community.Display.V1.FormattedValue": "03/08/2023",
    "estimatedclosedate": "2023-03-08"
  },
  {
    "@odata.etag": "W/\"110555983\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "02/17/2023",
    "mod@ified.on": "2023-02-17T16:45:02Z",
    "name": "RAJU-3/3/2022",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "216fc2e4-bf9a-ec11-b400-0022482f3db7",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "RAJU"
  },
  {
    "@odata.etag": "W/\"115621927\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "03/27/2023",
    "mod@ified.on": "2023-03-27T21:31:04Z",
    "name": "TestLocation-2/17/2023",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "2389ce1e-d6ae-ed11-aad1-0022482a9e1d",
    "estimatedclosedate@OData.Community.Display.V1.FormattedValue": "05/18/2023",
    "estimatedclosedate": "2023-05-18",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "TestLocation"
  },
  {
    "@odata.etag": "W/\"117640379\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "04/17/2023",
    "mod@ified.on": "2023-04-17T21:41:05Z",
    "name": "PETERSBURG PUBLIC LIBARY - RODOF SHOLOM BRANCH - ERATE-4/3/2023",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "4640872f-4ad2-ed11-a7c7-0022482a98ed",
    "estimatedclosedate@OData.Community.Display.V1.FormattedValue": "07/02/2023",
    "estimatedclosedate": "2023-07-02",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "PETERSBURG PUBLIC LIBARY - RODOF SHOLOM BRANCH - ERATE"
  },
  {
    "@odata.etag": "W/\"124338871\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "06/07/2023",
    "mod@ified.on": "2023-06-07T05:56:02Z",
    "name": "800123456Test_KA3-6/7/2023-Dedicated Internet",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "bbaa35d7-f704-ee11-8f6e-0022482a939e",
    "estimatedclosedate@OData.Community.Display.V1.FormattedValue": "09/05/2023",
    "estimatedclosedate": "2023-09-05",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "800123456Test_KA3"
  },
  {
    "@odata.etag": "W/\"130968047\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "08/29/2023",
    "mod@ified.on": "2023-08-29T19:05:53Z",
    "name": "Test _KarthikCompanyTest-02/17/2023",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "47bee227-e6ae-ed11-aad1-0022482a967e",
    "estimatedclosedate@OData.Community.Display.V1.FormattedValue": "05/18/2023",
    "estimatedclosedate": "2023-05-18",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "Test _KarthikCompanyTest"
  },
  {
    "@odata.etag": "W/\"130968060\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "08/29/2023",
    "mod@ified.on": "2023-08-29T19:05:56Z",
    "name": "Test _KarthikCompanyTest-02/17/2023",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "064daf90-e8ae-ed11-aad1-0022482a967e",
    "estimatedclosedate@OData.Community.Display.V1.FormattedValue": "05/18/2023",
    "estimatedclosedate": "2023-05-18",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "Test _KarthikCompanyTest"
  },
  {
    "@odata.etag": "W/\"130969977\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "08/29/2023",
    "mod@ified.on": "2023-08-29T19:33:13Z",
    "name": "qwerasdffffdw wdwwswdwdwdw-02/17/2023-Advanced Voice - SIP",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "c6f23bc2-e7ae-ed11-aad1-0022482a967e",
    "estimatedclosedate@OData.Community.Display.V1.FormattedValue": "05/18/2023",
    "estimatedclosedate": "2023-05-18",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "qwerasdffffdw wdwwswdwdwdw"
  },
  {
    "@odata.etag": "W/\"130971028\"",
    "cb_opportunitystage@OData.Community.Display.V1.FormattedValue": "Appointment Set",
    "cb_opportunitystage": 1,
    "modifiedon@OData.Community.Display.V1.FormattedValue": "08/29/2023",
    "mod@ified.on": "2023-08-29T19:55:35Z",
    "name": "dell-5/17/2022",
    "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue": "US Dollar",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "transactioncurrencyid",
    "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "transactioncurrency",
    "_transactioncurrencyid_value": "cdd1531b-f69f-e911-a96c-000d3a4e8ef8",
    "opportunityid": "0096721f-b4fa-473d-986a-4a33439cf322",
    "actualvalue@OData.Community.Display.V1.FormattedValue": "$1,000.00",
    "actualvalue": 1000,
    "estimatedclosedate@OData.Community.Display.V1.FormattedValue": "08/31/2023",
    "estimatedclosedate": "2023-08-31",
    "cb_upsideforecast@OData.Community.Display.V1.FormattedValue": "Forecast",
    "cb_upsideforecast": 108710001,
    "cb_lastactivitydate@OData.Community.Display.V1.FormattedValue": "08/23/2023",
    "cb_lastactivitydate": "2023-08-23T14:00:00Z",
    "parentaccountid.name@OData.Community.Display.V1.AttributeName": "name",
    "parentaccountid.name": "dell"
  }
];
